### ISSUE TITLE
Ninja-build package is a hard dependency 

### ISSUE THREAD

**Issue by lucas-coutinho** [PinguimBots/ssl-client#4]
Tried to compile the project from source, but i needed to install ninja-build package  via apt install before compile it.

**Comment by fschnee** [comment]
Meson has 3 backends:
- ninja
- visual studio on windows
- xcode on mac

You need at least 1 installed, on linux there is only one choice.

From [the Quickstart Guide](https://mesonbuild.com/Quick-guide.html):
> Ninja is only needed if you use the Ninja backend. Meson can also generate native VS and XCode project files.

Maybe we should link to that on the readme.
